
runs:
  image-build:
    tasks:
      build:
        taskRef:
          name: kaniko
          params:
            IMAGE: kodacd/sample-go-api
          workspaces:
          - taskWorkspace: source
            sourceWorkspace: $(KODACD_BUILD_WORKSPACE)
            # subPath: ""
      debug:
        runAfter:
        - build
        image: ubuntu
        script: |
          ls -lah /kodacd/build

      # hello:
      #   taskRef:
      #     name: curl # https://github.com/tektoncd/catalog/blob/main/task/curl/0.1/curl.yaml
      #     params:
      #       url: https://google.com
      #       options:
      #       - "-L"

      # goodbye:
      #   runAfter:
      #   - hello
      #   image: ubuntu
      #   script: printf "goodbye"
  # .dev:
  #   variables:
  #     HOST: dev-host
      
  # dev:
  #   extends:
  #   - .dev
  #   clone: {}
  #   # roles:
  #   # - name: k8s-reader
  #   # - name: aws-s3-reader
  #   # needs:
  #   #   egress:
  #   #   - 0.0.0.0/0
  #   #   serviceAccount:
  #   #   - superadmin
  #   tasks:
  #     ben-dev:
  #       image: bitnami/kubectl:latest
  #       script: |
  #         curl google.com
  #         kubectl get ns
  #     # build:
  #     #   image: ubuntu
  #     #   script: |
  #     #     echo "all repo files:"
  #     #     for f in $(bashArray(files()))
  #     #     do
  #     #       echo "    ${f}"
  #     #     done

  #     #     echo "test this"

  # # .test:
  # #   variables:
  # #     HOST: test-host

  # # .build:
  # #   tasks:
  # #   - name: build
  # #   - name: scan
  # #     script:
  # #       echo "hey $(HOST)"
  # #   - name: artifact

  # # dev-ci:
  # #   extends:
  # #   - .dev
  # #   - .build
  # #   tasks:
  # #     some-extra-dev-thing:
  # #       runAfter:
  # #       - build

  # # test-ci:
  # #   extends:
  # #   - .test
  # #   - .build