
runs:
  .dev:
    variables:
      HOST: dev-host
      
  dev-build:
    extends:
    - .dev
    tasks:
      build:
        image: ubuntu
        script: |
          echo "hello, $(HOST)\n"

          echo "all repo files:\n"

          for f in $(bashArray(files("pkg/.*")))
          do
            echo "${f}"
          done

  # .test:
  #   variables:
  #     HOST: test-host

  # .build:
  #   tasks:
  #   - name: build
  #   - name: scan
  #     script:
  #       echo "hey $(HOST)"
  #   - name: artifact

  # dev-ci:
  #   extends:
  #   - .dev
  #   - .build
  #   tasks:
  #     some-extra-dev-thing:
  #       runAfter:
  #       - build

  # test-ci:
  #   extends:
  #   - .test
  #   - .build